// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmbHa0h-AVSv-jukhW5qd7Ihh1e-MSgo0',
    appId: '1:296634681273:web:ff3f9a4264f1494b63d868',
    messagingSenderId: '296634681273',
    projectId: 'quizapp-fa480',
    authDomain: 'quizapp-fa480.firebaseapp.com',
    storageBucket: 'quizapp-fa480.appspot.com',
    measurementId: 'G-51MMGBYZV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5RJZKPdhxcpmr_dTUmjEk9hoY3qXjkWo',
    appId: '1:296634681273:android:206cb61e1852bc2063d868',
    messagingSenderId: '296634681273',
    projectId: 'quizapp-fa480',
    storageBucket: 'quizapp-fa480.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Cbu3jV7nIx1a9K6arlBr5w5JQs1Pp9U',
    appId: '1:296634681273:ios:75f81d5510e8ebf963d868',
    messagingSenderId: '296634681273',
    projectId: 'quizapp-fa480',
    storageBucket: 'quizapp-fa480.appspot.com',
    iosClientId: '296634681273-m8ro0187u0d67n0or1ethoff6kc79isi.apps.googleusercontent.com',
    iosBundleId: 'dev.yogan.quizzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Cbu3jV7nIx1a9K6arlBr5w5JQs1Pp9U',
    appId: '1:296634681273:ios:75f81d5510e8ebf963d868',
    messagingSenderId: '296634681273',
    projectId: 'quizapp-fa480',
    storageBucket: 'quizapp-fa480.appspot.com',
    iosClientId: '296634681273-m8ro0187u0d67n0or1ethoff6kc79isi.apps.googleusercontent.com',
    iosBundleId: 'dev.yogan.quizzer',
  );
}
